"use client";
import Head from "next/head";
import { useState } from "react";
import { FaAngleDoubleDown, FaAngleDoubleUp } from "react-icons/fa";
import { FaArrowRotateLeft, FaArrowRotateRight } from "react-icons/fa6";
import { GiRobotGolem } from "react-icons/gi";

export default function Home() {
  const [currentRotation, setCurrentRotation] = useState(0);

  function rotateRobot(degrees: number) {
    setCurrentRotation((prevRotation) => prevRotation + degrees);
  }

  function moveForward() {
    const direction = currentRotation % 360;
    const moveIcon =
      direction < 180 ? (
        <FaAngleDoubleUp className="absolute right-1 top-1 size-20" />
      ) : (
        <FaAngleDoubleUp className="absolute left-1 top-1 size-20 rotate-180" />
      );

    return <div className="relative">{moveIcon}</div>;
  }

  const Robot = ({ rotation }: { rotation: number }) => {
    return (
      <div style={{ transform: `rotate(${rotation}deg)` }}>
        <GiRobotGolem id="robot" className="size-40 fill-orange-400" />
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Hyper Robot Project</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[url('/background-texture-repeat.avif')]">
        <h1 className="font-sans-serif text-3xl">Hyper Robot Project 9000</h1>
        <div className="grid grid-cols-3 grid-rows-3 gap-3 bg-gray-300">
          <div id="1:1" className="size-40 bg-gray-600">
            <Robot rotation={currentRotation} />
          </div>
          <div id="1:2" className="size-40 bg-gray-600"></div>
          <div id="1:3" className="size-40 bg-gray-600"></div>
          <div id="2:1" className="size-40 bg-gray-600"></div>
          <div id="2:2" className="size-40 bg-gray-600"></div>
          <div id="2:3" className="size-40 bg-gray-600"></div>
          <div id="3:1" className="size-40 bg-gray-600"></div>
          <div id="3:2" className="size-40 bg-gray-600"></div>
          <div id="3:3" className="size-40 bg-gray-600"></div>
        </div>

        <div id="controls" className="mt-10 flex">
          <button
            type="button"
            className="size-20 bg-gray-200 p-1"
            id="left"
            onClick={() => rotateRobot(90)}
          >
            <FaArrowRotateLeft className="mx-auto size-20" />
          </button>
          {/* 
          --color-white: #ffffff;
    --color-grey-100: #f7f7f7;
    --color-grey-200: #efefef;
    --color-grey-300: #dbdbdb;
    --color-grey-400: #9b9b9b;
    --color-grey-500: #666666;
    --color-grey-600: #333333;
    --color-pop-orange: #e15a1d; #EFEAE5*/}
          <button
            type="button"
            id="move"
            className="size-20 bg-gray-200"
            onClick={moveForward}
            style={{ transform: `rotate(${currentRotation}deg)` }}
          >
            <FaAngleDoubleDown className="mx-auto size-20 p-1" />
          </button>
          <button
            type="button"
            id="right"
            className="size-20 bg-gray-200"
            onClick={() => {
              rotateRobot(-90);
            }}
          >
            <FaArrowRotateRight className="mx-auto size-20 p-1" />
          </button>
        </div>
      </main>
    </>
  );
}
